module.exports = {
    WithdrawalAddressTypes: {
        BITCOIN: 'bitcoin',
        PERFECTMONEY: 'perfectmoney',
        WIRETRANSFER: 'wiretransfer'
    },
    WithdrawalAddressDetailsTypes: {
        BITCOIN: { "bitcoin_address": "" },
        PERFECTMONEY: { "account_number": "", "account_name": "" },
        WIRETRANSFER: { "account_no": "", "account_name": "", "bank_name": "", "swift_code": "", "routing_number": "", "bank_address": "" }
    },
    AccountTypes: {
        SILVER: 'SILVER',
        PREMIUM: 'PREMIUM',
        GOLD: 'GOLD'
    },
    AccountStatuses: {
        UNVERIFIED: 'unverified',
        VERIFIED: 'verified'
    },
    AccountRoles: {
        MEMBER: 'member',
        ADMIN: 'admin'
    },
    TransactionStatuses: {
        PENDING: 'pending',
        COMPLETED: 'completed',
        FAILED: 'failed'
    },
    TradeStatuses: {
        OPEN: 'open',
        CLOSED: 'closed',
        CANCELLED: 'canceled'
    },
    OrderStatuses: {
        PENDING: 'pending',
        COMPLETED: 'completed'
    },
    Symbols: {
        CryptoPairs: {
            BTCUSD: 'BTC/USD',
            ETHUSD: 'ETH/USD',
            LTCUSD: 'LTC/USD',
            XRPUSD: 'XRP/USD',
            BCHUSD: 'BCH/USD',
            ADAUSD: 'ADA/USD',
            BNBUSD: 'BNB/USD',
            DOTUSD: 'DOT/USD',
            LINKUSD: 'LINK/USD',
            SOLUSD: 'SOL/USD',
            MATICUSD: 'MATIC/USD',
            AVAXUSD: 'AVAX/USD',
            SHIBUSD: 'SHIB/USD',
            DOGEUSD: 'DOGE/USD',
            UNIUSD: 'UNI/USD',
            BTCUSDT: 'BTC/USDT',
            ETHUSDT: 'ETH/USDT',
            ADAUSDT: 'ADA/USDT',
            BNBUSDT: 'BNB/USDT',
            DOGEUSDT: 'DOGE/USDT',
            SOLUSDT: 'SOL/USDT',
            MATICUSDT: 'MATIC/USDT',
            XRPUSDT: 'XRP/USDT',
            LINKUSDT: 'LINK/USDT',
            UNIUSDT: 'UNI/USDT',
            AVAXUSDT: 'AVAX/USDT',
        },
        ForexPairs: {
            EURUSD: 'EUR/USD',
            GBPUSD: 'GBP/USD',
            USDJPY: 'USD/JPY',
            AUDUSD: 'AUD/USD',
            USDCAD: 'USD/CAD',
            USDCHF: 'USD/CHF',
            NZDUSD: 'NZD/USD',
            EURGBP: 'EUR/GBP',
            EURJPY: 'EUR/JPY',
            GBPJPY: 'GBP/JPY',
            CHFJPY: 'CHF/JPY',
            EURAUD: 'EUR/AUD',
            EURCHF: 'EUR/CHF',
            EURUSD: 'EUR/USD',
            EURGBP: 'EUR/GBP',
            GBPCAD: 'GBP/CAD',
            GBPNZD: 'GBP/NZD',
            NZDJPY: 'NZD/JPY',
            NZDUSD: 'NZD/USD',
            NZDCHF: 'NZD/CHF',
            EURONZD: 'EUR/NZD',
            CADJPYm: 'CAD/JPYm',
            AUDJPYm: 'AUD/JPYm',
            USDCHF: 'USD/CHF',
            GBPAUD: 'GBP/AUD',
            USDTRY: 'USD/TRY',
            USDTHB: 'USD/THB',
            AUDUSD: 'AUD/USD',
            CADJPY: 'CAD/JPY',
            USDRUB: 'USD/RUB',
            EURCHF: 'EUR/CHF',
            NZDCHF: 'NZD/CHF',
            XAUUSD: 'XAU/USD',
            NZDJPY: 'NZD/JPY',
            CADJPY: 'CAD/JPY',
        },
        StocksPairs: {
            META: "Meta Platforms Inc",
            BA: "Boeing Co",
            AAPL: "Apple Inc",
            AMZN: "Amazon.com Inc",
            MSFT: "Microsoft Corp",
            NFLX: "Netflix Inc",
            MU: "Micron Technology Inc",
            GOOGL: "Alphabet Inc",
            SNAP: "Snap Inc",
            NVDA: "NVIDIA Corp",
            ACB: "Aurora Cannabis Inc",
            CGC: "Canopy Growth Corp",
            TSLA: "Tesla Inc",
            TWTR: "Twitter Inc",
            SBER: "Sberbank of Russia",
            CRON: "Cronos Group Inc",
            PFE: "Pfizer Inc",
            BAC: "Bank of America Corp",
            INTC: "Intel Corp",
            EA: "Electronic Arts Inc",
            SHOP: "Shopify Inc",
            PYPL: "PayPal Holdings Inc",
            ROKU: "Roku Inc",
            RBLX: "Roblox Corp",
            IBM: "IBM Corp",
            DIS: "Walt Disney Co",
            V: "Visa Inc",
            MA: "Mastercard Inc",
        }
    },
    Currencies: {
        USD: 'USD',
        EUR: 'EUR',
        GBP: 'GBP',
        JPY: 'JPY',
        AUD: 'AUD',
        CAD: 'CAD',
        CHF: 'CHF',
        CNY: 'CNY',
        SEK: 'SEK',
        NZD: 'NZD'
    },
};